-- Plugings
require("plugins.lazy")
require("plugins.lsp-zero")
require("plugins.cmp")
require("plugins.treesitter")
require("plugins.lualine")
require("plugins.indent-scope")
require("plugins.lua-snip")
require("plugins.bufferline")
require("plugins.none-ls")
require("plugins.lsp-saga")
